### ISSUE TITLE
preferred pronouns in user profiles

### ISSUE THREAD

**Issue by aletson** [aletson/votefinder-web#133]
as described in title _- reported by Alli🎃_

**Comment by rjmagley** [comment]
This is something I've been thinking about - it's just another text field present in a user profile, right? we don't need to do anything fancy with like dropdowns to have a user select from a predefined set or anything, just have them drop in their preferences and save?

**Comment by aletson** [comment]
Pretty much.

I remember having an extensive discussion about this in the Discord, but I do not remember the upshot of that.

**Comment by aletson** [comment]
I will be searching Discord today to go over the resolution discussed and will work on implementation this weekend.

**Comment by aletson** [comment]
I fixed outstanding issues post merge. To me this is good to go
