### ISSUE TITLE
update deps: Django 2.2

### ISSUE THREAD

**Issue by aletson** [aletson/votefinder-web#136]
As per the Django roadmap, 1.11 LTS falls out of support in April of next year. In order to avoid Votefinder falling out of support (as it did previous to active maintenance efforts), we need to upgrade it - so this issue actually has a **deadline**.

The fun part is that this needs to be done on local console so we need to copy the code base and actually spin up a dev server to do real development again.

- [x] Evaluate current depreciation warnings
- [x] Upgrade to 2.0.13
- [x] Reevaluate depreciation warnings
- [x] Upgrade to 2.1.14 or latest 2.1 branch release
- [x] Reevaluate depreciation warnings
- [x] Upgrade to 2.2.7 or latest 2.2 branch release
- [ ] (optional, but it'll save me a headache in 2021) Reevaluate depreciation warnings again

![image](https://user-images.githubusercontent.com/6288119/69575102-9d320200-0f97-11ea-91e3-2926e85dab4e.png)

**Comment by aletson** [comment]
https://docs.djangoproject.com/en/2.2/internals/deprecation/

**Comment by aletson** [comment]
Since 2.0 is out of support and 2.1 will be at EOY, no release to production before 2.2 is done. Whee!

**Comment by aletson** [comment]
Things that spring out as really obvious: 

- 2.0: Some database functions are going away. I don't think, but amn't sure, that I used any of them. (see https://docs.djangoproject.com/en/2.2/releases/1.9/#deprecated-features-1-9)
- 2.1: contrib.auth.views.login(), logout(), password_change(), password_change_done(), password_reset(), password_reset_done(), password_reset_confirm(), and password_reset_complete() will be removed. I believe I took care of all these during responsive reskin time but will need to check. This may jsut require moving to class-based views. (see https://docs.djangoproject.com/en/2.2/releases/1.11/#deprecated-features-1-11)

**Comment by rjmagley** [comment]
I can take a stab at helping with this at the end of December/start of January depending on my schedule, if you need a hand

**Comment by aletson** [comment]
Sure, whenever you have time feel free to jump in, once I have time to get a local dev env up on my laptop I will be starting a new feature branch for this

**Comment by aletson** [comment]
I will be working on this this weekend.

**Comment by aletson** [comment]
Forgot to push my progress. More updates soon.

**Comment by aletson** [comment]
The page parser works fine, so I think I'm comfortable here

**Comment by aletson** [comment]
login/logout is broken but I might know why

**Comment by aletson** [comment]
in fact, i did know why, it was across all the auth views, and i fixed it in 438de0d

i'm comfortable with where this is at
