### ISSUE TITLE
game stuck, can't refresh

### ISSUE THREAD

**Issue by aletson** [aletson/votefinder-web#205]
Dennis Lee's Food Crime Mafia is in a weird state. Can't refresh the game to read posts. Game thinks there are no players (added one manually to see what would happen). Posts for game in VF shows the OP twice. Did add factions at some point, removing them did nothing. _- reported by Epsilon_

**Comment by rjmagley** [comment]
game is https://votefinder.org/game/dennis-lees-food-crime
thread is https://forums.somethingawful.com/showthread.php?threadid=3933420

attempting to refresh leads to this image (waited half an hour for it to resolve):
![image](https://user-images.githubusercontent.com/20324985/88150406-f6097700-cbc6-11ea-83de-192b1969e37e.png)

can't access any logs to check or anything but it feels like it just doesn't know what to do, something in the OP is maybe causing some issues?

**Comment by rjmagley** [comment]
setting the OP to the phrase "testing" and trying to update again leads to the same behavior, so it's not choking on some formatting in the OP

**Comment by rjmagley** [comment]
the only other game on VF right now (a BNR game) refreshes without issue. other games were doing okay today?

**Comment by rjmagley** [comment]
suggested to close/reopen the thread and to disable autohammer, no dice. maybe check what's in the DB for this game? slug is "dennis-lees-food-crime"

**Comment by aletson** [comment]
i killed the game and readded it from the admin panel, nothing

**Comment by aletson** [comment]
may be fixed

**Comment by aletson** [comment]
specifically: related to add games. when there are duplicate post ids in the database, updates stop working because it sees duplicate posts on a `Post.get()` call which throws a 500

**Comment by aletson** [comment]
hypothesis is that `add_game` got pinged twice which brought in posts twice because add_game uses `Game.get_or_create()`, perhaps?

**Comment by aletson** [comment]
closed in 3.6.2a
