### ISSUE TITLE
Server error 500

### ISSUE THREAD

**Issue by aletson** [aletson/votefinder-web#232]
When adding a votecount comment I get Server Error 500. _- reported by Cpig_

**Comment by capitalistpig** [comment]
Cpig here - 
![se500](https://user-images.githubusercontent.com/74389606/101993345-cb0fe480-3c87-11eb-8fe4-f9616e185224.JPG)
![se501](https://user-images.githubusercontent.com/74389606/101993347-ce0ad500-3c87-11eb-9b34-4bbc516da3fa.JPG)
