### ISSUE TITLE
MySQL migrations

### ISSUE THREAD

**Issue by aletson** [aletson/votefinder-web#36]
I don't feel that it is needed to tie this into the application necessarily, but it would be nice to leave vf-skel.sql unchanged moving forward and just having run-once ALTER TABLE commands. Maybe a `version` table in the database which CI could check against, then run all files > that version?

**Comment by velinath** [comment]
- [X] add version 1 to db_skel.sql
- [ ] add to beta db manually
- [ ] modify workflow to watch `sql/` directory for `migration_#.sql` for `SELECT version FROM version` if version+1 exists then apply to db
- [ ] test with sample sql
- [ ] promote to prod

**Comment by velinath** [comment]
mariadb client installed on jenkins

**Comment by velinath** [comment]
CI job has been updated to support migrations.

**Comment by velinath** [comment]
Tested and working in Dev. Ready to push to the prod pipeline task. Just need to make sure `migration_version` table is created and contains `1` base value.

**Comment by aletson** [comment]
Migration added to prod deploy CI job

**Comment by aletson** [comment]
I did in fact validate this yes
