### ISSUE TITLE
Generate signup image

### ISSUE THREAD

**Issue by aletson** [aletson/votefinder-web#4]
Currently, it's hard to tell exactly what games are open and taking signups. Votefinder uses PIL to generate votecount images; let's leverage that to create a list of games currently in signup. This might require us to change the way that Votefinder handles games - have them automatically start at day 0 instead of day 1 when the thread is registered in votefinder, then let the mods reset the day 1 post as they do now. If we did that, we could just select where gameday = 0 and pull those games.

Might not hurt to add a field for mods to note how many slots are in their game, either. That way it'd be abundantly clear - "7 of 15 signed up", kind of thing.

**Comment by epsilonplus** [comment]
Where would this go? Something like the front page/first post of the Mafia thread? Could this potentially be used to take signups also; if the game starts at day 0, use something like the current vote counting logic to scan the thread for ##signup and ##unsignup?

**Comment by velinath** [comment]
yeah I think that was the idea when it was originally proposed --

I think it would be pretty neat if we had automatic signups, but would need to add a toggle as I would imagine some mods may not want that turned on / may want to add presigns.

**Comment by velinath** [comment]
Changing default currentday to 0 should help with this, as then we can have games created on day 0 - can use that to determine games not started yet.

**Comment by aletson** [comment]
Superseded by #160.
